server:
  port: 14000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /vt

spring:
  application:
    name: vector_tile
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//172.20.3.240:1521/orcl
    username: ssjt
    password: ssjt
#    hikari:
#      auto-commit: true
#      maximum-pool-size: 8
#      minimum-idle: 2
#      idle-timeout: 3000
#      connection-test-query: select 1
#      connection-timeout: 3000
#    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml,edu.zju.gis.vectortile.mapper/*.xml
logging:
  level:
    edu.zju.gis.vectortile.dao: DEBUG