server:
  port: 14000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /test

spring:
  application:
    name: vector_tile
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//172.20.3.240:1521/orcl
    username: ssjt
    password: ssjt
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml,edu.zju.gis.vectorTile.mapper/*.xml